name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  # -----------------------------------------------------------------
  # JOB 1: BUILD
  # -----------------------------------------------------------------
  # We build first to catch syntax errors early and to compile the
  # 'dist' folder that the production preview needs.
  build:
    name: Build Project
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup PNPM with version 9
      - uses: pnpm/action-setup@v3
        with:
          version: 9

      # Setup Node and enable dependency caching automatically
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Astro Site
        # 👇 INSERT OTHER ENV VARS HERE
        # Since this is a generic starter, add any secrets required
        # for the build process (like CMS tokens, Analytics IDs) below.
        env:
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
          # PUBLIC_API_KEY: ${{ secrets.PUBLIC_API_KEY }}
        run: pnpm build

      # Save the built 'dist' folder to pass it to the Test job
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/
          retention-days: 1

  # -----------------------------------------------------------------
  # JOB 2: TEST
  # -----------------------------------------------------------------
  # This only runs if 'build' succeeds. It reuses the 'dist' folder.
  test:
    name: E2E Tests
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Download the site we built in the previous job
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist/

      # --- BROWSER CACHING START ---
      # This checks if the Playwright version changed.
      # If not, it restores browsers from cache to save ~2 mins.
      - name: Get installed Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(pnpm ls @playwright/test | grep @playwright/test | sed 's/.*@playwright\/test //')" >> $GITHUB_ENV

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm exec playwright install --with-deps
      # --- BROWSER CACHING END ---

      # Run the tests using your package.json script
      - name: Run Playwright tests
        run: pnpm test:e2e

      # Upload the HTML report so you can see screenshots of failures
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
